name: CI

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  create:
    tags:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/TagBot.yml'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/TagBot.yml'
jobs:
  ratequery:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/rate_limit
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

